[colors.primary]
background = "#222222"
foreground = "#F7F1FF"

[colors.cursor]
text = "#222222"
cursor = "#F7F1FF"

[colors.vi_mode_cursor]
text = "#222222"
cursor = "#F7F1FF"

[colors.search.matches]
foreground = "#222222"
background = "#F7F1FF"

[colors.search.focused_match]
foreground = "#222222"
background = "#FD9353"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#222222"
background = "#F7F1FF"

[colors.selection]
text = "#222222"
background = "#948AE3"

[colors.normal]
black = "#363537"
red = "#FC618D"
green = "#7BD88F"
yellow = "#FCE566"
blue = "#FD9353"
magenta = "#948AE3"
cyan = "#5AD4E6"
white = "#F7F1FF"

[colors.bright]
black = "#69676C"
red = "#FC618D"
green = "#7BD88F"
yellow = "#FCE566"
blue = "#FD9353"
magenta = "#948AE3"
cyan = "#5AD4E6"
white = "#F7F1FF"

[colors.dim]
black = "#525053"
red = "#FC618D"
green = "#7BD88F"
yellow = "#FCE566"
blue = "#FD9353"
magenta = "#948AE3"
cyan = "#5AD4E6"
white = "#F7F1FF"
