accent = "#948AE3"
cursor = "#F7F1FF"
foreground = "#F7F1FF"
background = "#222222"
selection_foreground = "#222222"
selection_background = "#948AE3"

color0 = "#363537"
color1 = "#FC618D"
color2 = "#7BD88F"
color3 = "#FCE566"
color4 = "#FD9353"
color5 = "#948AE3"
color6 = "#5AD4E6"
color7 = "#F7F1FF"
color8 = "#69676C"
color9 = "#FC618D"
color10 = "#7BD88F"
color11 = "#FCE566"
color12 = "#FD9353"
color13 = "#948AE3"
color14 = "#5AD4E6"
color15 = "#F7F1FF"
