accent = "#948AE3"
cursor = "#F7F1FF"
foreground = "#F7F1FF"
background = "#222222"
selection_foreground = "#222222"
selection_background = "#948AE3"

color0 = "#131313"
color1 = "#FC618D"
color2 = "#7BD88F"
color3 = "#FCE566"
color4 = "#5AD4E6"
color5 = "#948AE3"
color6 = "#FD9353"
color7 = "#FFFFFF"
color8 = "#191919"
color9 = "#FC618D"
color10 = "#7BD88F"
color11 = "#FCE566"
color12 = "#5AD4E6"
color13 = "#948AE3"
color14 = "#FD9353"
color15 = "#FFFFFF"
