background #222222
foreground #F7F1FF

selection_foreground #222222
selection_background #948AE3
cursor #F7F1FF
cursor_text_color #222222
active_border_color #948AE3
active_tab_background #948AE3

# black
color0  #363537
color8  #69676C

# red
color1  #FC618D
color9  #FC618D

# green
color2  #7BD88F
color10 #7BD88F

# yellow
color3  #FCE566
color11 #FCE566

# blue
color4  #FD9353
color12 #FD9353

# magenta
color5  #948AE3
color13 #948AE3

# cyan
color6  #5AD4E6
color14 #5AD4E6

# white
color7  #F7F1FF
color15 #F7F1FF
